// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operate.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Op int32

const (
	Op_STATUS Op = 0
	Op_START  Op = 1
	Op_STOP   Op = 2
)

var Op_name = map[int32]string{
	0: "STATUS",
	1: "START",
	2: "STOP",
}

var Op_value = map[string]int32{
	"STATUS": 0,
	"START":  1,
	"STOP":   2,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db7544804fed5e49, []int{0}
}

type Instruct struct {
	Op                   Op       `protobuf:"varint,1,opt,name=op,proto3,enum=pb.Op" json:"op,omitempty"`
	App                  string   `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instruct) Reset()         { *m = Instruct{} }
func (m *Instruct) String() string { return proto.CompactTextString(m) }
func (*Instruct) ProtoMessage()    {}
func (*Instruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7544804fed5e49, []int{0}
}

func (m *Instruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instruct.Unmarshal(m, b)
}
func (m *Instruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instruct.Marshal(b, m, deterministic)
}
func (m *Instruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instruct.Merge(m, src)
}
func (m *Instruct) XXX_Size() int {
	return xxx_messageInfo_Instruct.Size(m)
}
func (m *Instruct) XXX_DiscardUnknown() {
	xxx_messageInfo_Instruct.DiscardUnknown(m)
}

var xxx_messageInfo_Instruct proto.InternalMessageInfo

func (m *Instruct) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_STATUS
}

func (m *Instruct) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Op", Op_name, Op_value)
	proto.RegisterType((*Instruct)(nil), "pb.Instruct")
}

func init() { proto.RegisterFile("operate.proto", fileDescriptor_db7544804fed5e49) }

var fileDescriptor_db7544804fed5e49 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2f, 0x48, 0x2d,
	0x4a, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe1,
	0xe2, 0xf0, 0xcc, 0x2b, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0xca, 0x2f, 0x90,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x62, 0xd3, 0x2b, 0x48, 0xd2, 0xf3, 0x2f, 0x08, 0x62, 0xca,
	0x2f, 0x10, 0x12, 0xe0, 0x62, 0x4e, 0x2c, 0x28, 0x90, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0x31, 0xb5, 0x54, 0xb9, 0x98, 0xfc, 0x0b, 0x84, 0xb8, 0xb8, 0xd8, 0x82, 0x43, 0x1c, 0x43, 0x42,
	0x83, 0x05, 0x18, 0x84, 0x38, 0xb9, 0x58, 0x83, 0x43, 0x1c, 0x83, 0x42, 0x04, 0x18, 0x85, 0x38,
	0xb8, 0x58, 0x82, 0x43, 0xfc, 0x03, 0x04, 0x98, 0x92, 0xd8, 0xc0, 0xf6, 0x18, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xc1, 0xd9, 0xc7, 0x5b, 0x78, 0x00, 0x00, 0x00,
}
